# Generated by Django 3.0.2 on 2020-01-13 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Creation date', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Modified date', verbose_name='modified_at')),
                ('name', models.CharField(max_length=140, verbose_name='circle name')),
                ('slug_name', models.SlugField(unique=True)),
                ('about', models.TextField(verbose_name='circle description')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='circles/pictures')),
                ('rides_offered', models.PositiveIntegerField(default=0)),
                ('rides_taken', models.PositiveIntegerField(default=0)),
                ('verified', models.BooleanField(default=False, help_text='Verified circles that are known as official communities.', verbose_name='verified circle')),
                ('is_puclic', models.BooleanField(default=True, help_text='Public circles are listed in the main page to join it for everyone.')),
                ('is_limited', models.BooleanField(default=False, help_text='Limited circles can grow up to a fixed number of members.', verbose_name='limited')),
                ('merbers_limit', models.PositiveIntegerField(default=0, help_text='If circle is limited, this will be the limit of members in the circle.')),
            ],
            options={
                'ordering': ['-rides_taken', '-rides_offered'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
