# Generated by Django 3.0.2 on 2020-01-13 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circle',
            old_name='is_puclic',
            new_name='is_public',
        ),
        migrations.RenameField(
            model_name='circle',
            old_name='verified',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='circle',
            old_name='merbers_limit',
            new_name='members_limit',
        ),
    ]
